# lateral-movement.Containerfile
# ------------------------------------------------------------
# Linux Lateral Movement Lab - Multi-Container Podman Lab
#
# WARNING: Intentionally vulnerable. Run only on an isolated host and never
# expose these services to a real network.
#
# Simulates a small corporate network with:
#   - web-server (compromised, ingress from attacker network)
#   - file-server (NFS share with no_root_squash)
#   - db-server  (PostgreSQL + Redis, internal credentials)
#
# Networks:
#   lateral-net (10.89.50.0/24) - All hosts on flat internal network
#   attacker-net (10.89.0.0/24) - Attacker workstation
#
# The web-server is dual-homed (attacker-net + lateral-net).
# All other servers are lateral-net only.
#
# Build:
#   podman build -t lateral-web --target web-server \
#       -f lateral-movement.Containerfile .
#   podman build -t lateral-file --target file-server \
#       -f lateral-movement.Containerfile .
#   podman build -t lateral-db --target db-server \
#       -f lateral-movement.Containerfile .
#
# Setup:
#   podman network create attacker-net --subnet 10.89.0.0/24
#   podman network create lateral-net --subnet 10.89.50.0/24
#
#   podman run -d --name web-server --network attacker-net \
#       --network lateral-net --cap-add NET_ADMIN lateral-web
#   podman run -d --name file-server --network lateral-net \
#       --cap-add SYS_ADMIN lateral-file
#   podman run -d --name db-server --network lateral-net lateral-db
#
# Scenario:
#   Initial compromise: RCE on web-server (PHP web app vulnerability).
#   Objective: Gain root on db-server.
#
# Intended lateral movement path:
#   1. Enumerate SSH material on web-server -> find key for file-server
#   2. SSH to file-server -> notice NFS mount with no_root_squash
#   3. Create SUID bash on NFS share -> executes as root on db-server
#   4. OR: Discover DB credentials in web-server configs -> connect to Redis
#      on db-server -> write SSH authorized_keys
#
# ------------------------------------------------------------

# -- STAGE 1: Web Server (Initial Compromise) --
FROM docker.io/alpine:latest AS web-server

RUN apk add --no-cache \
    bash \
    nginx \
    php83 \
    php83-fpm \
    php83-curl \
    php83-json \
    openssh-server \
    openssh-client \
    netcat-openbsd \
    curl \
    wget \
    procps \
    iproute2 \
    vim \
    nfs-utils

# SSH setup
RUN ssh-keygen -A
RUN echo 'root:webadmin123' | chpasswd
RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config

# Generate SSH key that has access to file-server
RUN ssh-keygen -t ed25519 -N '' -f /root/.ssh/id_ed25519
RUN printf '%s\n' \
    'Host file-server' \
    '    HostName 10.89.50.20' \
    '    User root' \
    '    IdentityFile ~/.ssh/id_ed25519' \
    > /root/.ssh/config
RUN chmod 600 /root/.ssh/config

# Database configuration file (contains credentials for db-server)
RUN printf '%s\n' \
    '# Web Application Configuration' \
    '# Generated by ansible - DO NOT EDIT' \
    '' \
    'DB_HOST=10.89.50.30' \
    'DB_PORT=5432' \
    'DB_NAME=webapp_production' \
    'DB_USER=webapp_user' \
    'DB_PASS=S3cur3W3bAppP@ss!' \
    '' \
    'REDIS_HOST=10.89.50.30' \
    'REDIS_PORT=6379' \
    'REDIS_PASS=' \
    '' \
    'SECRET_KEY=super-secret-webapp-key-change-in-production' \
    '' \
    '# Internal API endpoints' \
    'FILE_API=http://file-server.internal:8080/api/v1/files' \
    'DB_API=http://db-server.internal:9090/api/v1/query' \
    > /etc/webapp/config.env
RUN chmod 600 /etc/webapp/config.env

# A "vulnerable" PHP page - simulates a simple RCE vector
RUN printf '%s\n' \
    '<?php' \
    '// DEBUG endpoint - remove in production!' \
    'if (isset($_GET["cmd"])) {' \
    '    echo "<pre>";' \
    '    system($_GET["cmd"]);' \
    '    echo "</pre>";' \
    '}' \
    '?>' \
    > /var/www/html/debug.php

# Bash history with interesting artifacts (simulates a real user)
RUN printf '%s\n' \
    'ssh root@file-server' \
    'ssh root@10.89.50.20' \
    'mysql -u webapp_user -pS3cur3W3bAppP@ss! -h 10.89.50.30' \
    'ssh -i ~/.ssh/id_ed25519 root@file-server' \
    'cat /etc/webapp/config.env' \
    'ansible-playbook -i hosts deploy.yml' \
    'vim /etc/webapp/config.env' \
    > /root/.bash_history

# Nginx config
RUN printf '%s\n' \
    'server {' \
    '    listen 80 default_server;' \
    '    root /var/www/html;' \
    '    index index.html index.php;' \
    '    location ~ \.php$ {' \
    '        fastcgi_pass 127.0.0.1:9000;' \
    '        fastcgi_index index.php;' \
    '        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;' \
    '        include fastcgi_params;' \
    '    }' \
    '}' \
    > /etc/nginx/http.d/default.conf

RUN mkdir -p /run/nginx /var/www/html /etc/webapp

RUN printf '%s\n' \
    '#!/bin/sh' \
    'set -e' \
    'php-fpm83 -D 2>/dev/null || php-fpm83 2>/dev/null || true' \
    'nginx' \
    '/usr/sbin/sshd' \
    'echo "[+] Web server running: HTTP:80, SSH:22"' \
    'echo "    Debug endpoint: http://localhost/debug.php?cmd=id"' \
    'echo "    Config file: /etc/webapp/config.env"' \
    'echo "    SSH key: ~/.ssh/id_ed25519 (has access to file-server)"' \
    'tail -f /dev/null' \
    > /entrypoint.sh && chmod +x /entrypoint.sh

CMD ["/entrypoint.sh"]

EXPOSE 80 22


# -- STAGE 2: File Server (NFS with no_root_squash) --
FROM docker.io/alpine:latest AS file-server

RUN apk add --no-cache \
    bash \
    openssh-server \
    openssh-client \
    nfs-utils \
    netcat-openbsd \
    curl \
    wget \
    procps \
    iproute2 \
    vim \
    python3

# SSH setup
RUN ssh-keygen -A
RUN echo 'root:fileadmin456' | chpasswd
RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config

RUN mkdir -p /root/.ssh && chmod 700 /root/.ssh

# ATTACKER/STUDENT: Copy web-server's public key here so web-server can SSH in
# This is done at runtime via the setup script

# Create the shared directory (will be NFS-exported)
RUN mkdir -p /srv/nfs/shared /srv/nfs/homes
RUN chmod 777 /srv/nfs/shared

# Fake user data on NFS share
RUN printf '%s\n' \
    'This is a shared internal file server.' \
    'Mounted on: web-server, db-server, all developer workstations' \
    'NFS export options: rw,no_root_squash,sync' \
    '' \
    'The no_root_squash option means root on any client' \
    'has root privileges on this share.' \
    > /srv/nfs/shared/README.txt

RUN printf '%s\n' \
    '#!/bin/sh' \
    'set -e' \
    '' \
    '# Set up NFS exports' \
    'echo "/srv/nfs/shared *(rw,sync,no_root_squash,no_subtree_check)" > /etc/exports' \
    'echo "/srv/nfs/homes  *(rw,sync,no_root_squash,no_subtree_check)" >> /etc/exports' \
    '' \
    '# Start NFS services' \
    'exportfs -r 2>/dev/null || true' \
    '' \
    '# rpcbind' \
    'rpcbind 2>/dev/null || true' \
    'sleep 1' \
    '' \
    '# NFS server - may need different daemon names on Alpine' \
    'rpc.nfsd 8 2>/dev/null || /usr/sbin/rpc.nfsd 8 2>/dev/null || true' \
    'rpc.mountd 2>/dev/null || /usr/sbin/rpc.mountd 2>/dev/null || true' \
    '' \
    'echo "[+] NFS exports:"' \
    'showmount -e localhost 2>/dev/null || exportfs -v' \
    '' \
    '# Start SSH' \
    '/usr/sbin/sshd' \
    '' \
    'echo "[+] File server running: SSH:22, NFS:2049"' \
    'echo "    NFS share: /srv/nfs/shared (no_root_squash!)"' \
    'echo "    Lateral movement vector: SUID binary on NFS share"' \
    '' \
    'tail -f /dev/null' \
    > /entrypoint.sh && chmod +x /entrypoint.sh

CMD ["/entrypoint.sh"]

EXPOSE 22 2049 111


# -- STAGE 3: Database Server (Final Target) --
FROM docker.io/alpine:latest AS db-server

RUN apk add --no-cache \
    bash \
    openssh-server \
    openssh-client \
    postgresql \
    redis \
    nfs-utils \
    netcat-openbsd \
    curl \
    wget \
    procps \
    iproute2 \
    vim \
    python3

# SSH setup
RUN ssh-keygen -A
RUN echo 'root:dbadmin789' | chpasswd
RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config

RUN mkdir -p /root/.ssh && chmod 700 /root/.ssh

# The file-server's and web-server's SSH keys need access here for the lab
# Added at runtime

# PostgreSQL setup
RUN mkdir -p /run/postgresql /var/lib/postgresql/data
RUN chown -R postgres:postgres /var/lib/postgresql /run/postgresql
RUN su - postgres -c "initdb -D /var/lib/postgresql/data" 2>/dev/null || true

# Configure PostgreSQL for network access
RUN echo "listen_addresses = '*'" >> /var/lib/postgresql/data/postgresql.conf
RUN echo "host all all 10.89.50.0/24 md5" >> /var/lib/postgresql/data/pg_hba.conf

# Redis setup (no authentication - vulnerable)
RUN sed -i 's/^bind .*/bind 0.0.0.0/' /etc/redis.conf 2>/dev/null || true
RUN sed -i 's/^protected-mode yes/protected-mode no/' /etc/redis.conf 2>/dev/null || true

# Create the Flag - objective marker
RUN printf '%s\n' \
    'FLAG{LATERAL_MOVEMENT_COMPLETE_NFS_SUID_ROOT}' \
    > /root/FLAG.txt

RUN printf '%s\n' \
    'CONGRATULATIONS!' \
    '' \
    'You have successfully performed lateral movement from the web server' \
    'through the file server to gain root on the database server.' \
    '' \
    'Technique used: NFS no_root_squash + SUID binary' \
    '' \
    'Alternative paths:' \
    '  - Redis unauthorized access -> SSH authorized_keys write' \
    '  - Database credentials from web-server config -> PostgreSQL' \
    '    post-exploitation (PL/pgSQL UDF execution)' \
    '' \
    'FLAG{LATERAL_MOVEMENT_COMPLETE_NFS_SUID_ROOT}' \
    > /root/CONGRATULATIONS.txt

# Mount NFS share from file-server (simulates existing infrastructure)
RUN mkdir -p /mnt/nfs/shared

# Entrypoint
RUN printf '%s\n' \
    '#!/bin/sh' \
    'set -e' \
    '' \
    '# Start PostgreSQL' \
    'su - postgres -c "pg_ctl -D /var/lib/postgresql/data -l /var/log/postgresql.log start" 2>/dev/null || true' \
    'sleep 2' \
    '' \
    '# Create webapp database (if not exists)' \
    'su - postgres -c "psql -c \\"CREATE USER webapp_user WITH PASSWORD \\"'"'"'S3cur3W3bAppP@ss!'"'"'\\";" " 2>/dev/null || true' \
    'su - postgres -c "psql -c \\"CREATE DATABASE webapp_production OWNER webapp_user;\\" " 2>/dev/null || true' \
    'su - postgres -c "psql -d webapp_production -c \\"CREATE TABLE IF NOT EXISTS secrets (id SERIAL PRIMARY KEY, name TEXT, value TEXT);\\" " 2>/dev/null || true' \
    'su - postgres -c "psql -d webapp_production -c \\"INSERT INTO secrets (name, value) VALUES (\\"'"'"'api_key'"'"'", \\"'"'"'AKIAIOSFODNN7EXAMPLE'"'"'") ON CONFLICT DO NOTHING;\\" " 2>/dev/null || true' \
    '' \
    '# Start Redis (no auth)' \
    'redis-server /etc/redis.conf --daemonize yes 2>/dev/null || redis-server --daemonize yes 2>/dev/null || true' \
    '' \
    '# Mount NFS share from file-server (attempt)' \
    'mount -t nfs 10.89.50.20:/srv/nfs/shared /mnt/nfs/shared -o nolock,vers=3 2>/dev/null || true' \
    'sleep 1' \
    'if mount | grep -q nfs; then' \
    '    echo "[+] NFS share mounted from file-server (no_root_squash)"' \
    'else' \
    '    echo "[!] NFS mount failed - run '"'"'mount -t nfs 10.89.50.20:/srv/nfs/shared /mnt/nfs/shared -o nolock'"'"'"' \
    'fi' \
    '' \
    '# Start SSH' \
    '/usr/sbin/sshd' \
    '' \
    'echo "[+] Database server running:"' \
    'echo "    PostgreSQL: 5432 (user: webapp_user)"' \
    'echo "    Redis: 6379 (no authentication!)"' \
    'echo "    SSH: 22"' \
    'echo "    NFS mount: /mnt/nfs/shared"' \
    'echo ""' \
    'echo "    Flag location: /root/FLAG.txt"' \
    '' \
    'tail -f /dev/null' \
    > /entrypoint.sh && chmod +x /entrypoint.sh

CMD ["/entrypoint.sh"]

EXPOSE 22 5432 6379
